# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [3]:
'''
np.zeros((2, 3))會產生真正的0陣列；np.empty((2, 3))是產生一個近似於0的陣列。
np.empty可以用於只是想要初始化，但之後就會數值覆寫過的情況。
'''

'\nYour Code\n'

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [2]:
# 記得先 Import 正確的套件
import numpy as np

a = np.random.rand(3,4)
a = a * 50
print(a)

[[25.63624886 25.32828711 46.99326059 20.34473684]
 [ 4.74001244 20.64269705  9.47529045 27.13252843]
 [18.9082916  18.6525293  22.31176278 26.75032637]]


In [4]:
# 參考解答

print(a.round())
print(np.round(a))

[[26. 25. 47. 20.]
 [ 5. 21.  9. 27.]
 [19. 19. 22. 27.]]
[[26. 25. 47. 20.]
 [ 5. 21.  9. 27.]
 [19. 19. 22. 27.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [17]:
m = 20
n = 40

a = np.random.rand(3,4) * (n - m)
print(a)
print(a%1)

[[16.26580405 15.71371054 13.12346968 16.72311813]
 [16.5860291   6.92965541 18.55936391  9.63915792]
 [11.45061418 13.87105063 15.39039528 12.13039565]]
[[0.26580405 0.71371054 0.12346968 0.72311813]
 [0.5860291  0.92965541 0.55936391 0.63915792]
 [0.45061418 0.87105063 0.39039528 0.13039565]]


In [18]:
print(a - a%1)
print((a - a%1) + m)

[[16. 15. 13. 16.]
 [16.  6. 18.  9.]
 [11. 13. 15. 12.]]
[[36. 35. 33. 36.]
 [36. 26. 38. 29.]
 [31. 33. 35. 32.]]
