# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



- sum()是Python內建的函式，所有型態皆可以用。
- np.sum(a)跟sum(a)是陣列的函式，差別在於定義在np 或是 array之下。

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [4]:
a = np.random.random((5, 5))
print(a)

b = (a - a.min()) / (a.max() - a.min())
print(b)

[[0.13652102 0.40268825 0.15655425 0.58389094 0.50833515]
 [0.20319522 0.2896717  0.40250659 0.87387124 0.70273396]
 [0.40945227 0.3582164  0.16355667 0.27049494 0.76966874]
 [0.39126062 0.35768211 0.30684214 0.18210558 0.86267736]
 [0.66638746 0.19628987 0.23375652 0.17222202 0.6980108 ]]
[[0.         0.36097802 0.02716921 0.6067265  0.50425716]
 [0.09042406 0.20770411 0.36073165 1.         0.76790231]
 [0.37015144 0.30066496 0.03666595 0.18169645 0.85867977]
 [0.34547978 0.29994035 0.2309908  0.06182213 0.98481877]
 [0.71860891 0.08105896 0.13187152 0.04841797 0.76149673]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [6]:
c = np.random.random(10)
print(c)

c[c.argmax()]=-1
print(c)

[0.51083016 0.10396543 0.37005143 0.7980021  0.28670391 0.67449402
 0.06800011 0.83941937 0.60685408 0.99885811]
[ 0.51083016  0.10396543  0.37005143  0.7980021   0.28670391  0.67449402
  0.06800011  0.83941937  0.60685408 -1.        ]
